### ISSUE TITLE
HTML5up licensing

### ISSUE THREAD

**Issue by alejandroandreu** [stellarproject/causeway#1]
I'm sorry to be a partypooper, but this came to mind while checking out the code of stellarproject.io :sweat_smile: 

HTML5up.net has a [license](https://html5up.net/license) which states that attribution must be given to them somewhere in the website, and I didn't see any mention in the stellarproject.io.

Attribution-free themes can be found at [Pixelarity](https://pixelarity.com/), but its [license](https://pixelarity.com/license) doesn't permit to make its code publicly available.

**Comment by ehazlett** [comment]
Credit added to readme.  Thanks!
